// === VIDEO PLACEHOLDER BARU (YouTube Embed) ===
const videoMakanan = "https://www.youtube.com/embed/F-Bq02-x_fE";
const videoKerajinan = "https://www.youtube.com/embed/8-jF-TqT4-E";
const videoJasa = "https://www.youtube.com/embed/1Xp_imnLY4U";

// === PRODUK PLACEHOLDER BARU ===
const foodProducts = [
  { id: "p1", name: "Menu Andalan", price: 35000, description: "Paket paling populer dan direkomendasikan.", image_url: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?ixlib=rb-4.0.3&auto=format&fit=crop&w=870&q=80" },
  { id: "p2", name: "Menu Pelengkap", price: 15000, description: "Tambahan yang sempurna untuk hidangan utama.", image_url: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?ixlib=rb-4.0.3&auto=format&fit=crop&w=870&q=80" }
];
const serviceProducts = [
  { id: "p1", name: "Layanan Standar", price: 75000, description: "Solusi cepat dan efisien untuk kebutuhan Anda.", image_url: "https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?ixlib=rb-4.0.3&auto=format&fit=crop&w=870&q=80" },
  { id: "p2", name: "Layanan Premium", price: 250000, description: "Perawatan lengkap dan mendalam.", image_url: "https://images.unsplash.com/photo-1587573089734-09cb69c0f11a?ixlib=rb-4.0.3&auto=format&fit=crop&w=870&q=80" }
];
const shopProducts = [
  { id: "p1", name: "Produk Terlaris", price: 120000, description: "Item yang paling dicari oleh pelanggan.", image_url: "https://images.unsplash.com/photo-1578491793108-d1e3e05f560a?ixlib=rb-4.0.3&auto=format&fit=crop&w=870&q=80" },
  { id: "p2", name: "Souvenir Khas", price: 45000, description: "Cinderamata unik untuk oleh-oleh.", image_url: "https://images.unsplash.com/photo-1620799140414-b291c3d9b736?ixlib=rb-4.0.3&auto=format&fit=crop&w=870&q=80" }
];

export const umkmData = [
  {
    id: 1,
    name: "Gudeg Yu Djum Wijilan 167",
    category: "Makanan",
    subcategory: "Gudeg Tradisional",
    phone: "0274512345",
    priceRange: [20000, 50000],
    paymentMethods: ["Tunai", "QRIS", "GoPay", "OVO"],
    lastUpdated: "2025-10-30",
    reviewsList: [
      { id: "r1", user: "Budi Santoso", rating: 5, text: "Gudegnya paling legendaris! ...", date: "2025-10-28" },
      { id: "r2", user: "Anita Wijaya", rating: 4, text: "Tempatnya klasik dan otentik. ...", date: "2025-10-25" },
    ],
    owner: { name: "Yu Djum", joined: "2024-01-15", verified: true },
    rating: 99,
    reviews: 303,
    location: "Jl. Wijilan No. 167, Kraton",
    distance: "10 min",
    priceFrom: 25000,
    latitude: -7.8053,
    longitude: 110.3708,
    images: [
      "https://homestaydijogja.net/wp-content/uploads/2024/07/Gudeg-Yu-Djum-Wijilan-167.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8R-dfiqCMCZz-IKAo5INnRSF3zrTu1iKtcADpiVPs_HmJAJ6QZXP3jVeidHisCcJdoUs&usqp=CAU",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRk90L6IKJov7qLO1GVpw8r1Bcq420urS-rRQ&s",
      "https://statik.tempo.co/data/2019/02/17/id_820192/820192_720.jpg",
      "https://i.gojekapi.com/darkroom/gofood-indonesia/v2/images/uploads/19dc5ee9-4256-4838-8c29-1f341c140884_Go-Biz_20211223_105032.jpeg"
    ],
    description: "Gudeg Yu Djum adalah salah satu pelopor gudeg kering paling terkenal di Yogyakarta. Usaha ini bermula pada tahun 1950-an di sebuah dapur rumahan yang sederhana. Cita rasanya yang khas datang dari proses memasak tradisional menggunakan kayu bakar, santan pekat, serta bumbu-bumbu rempah yang diolah dalam waktu berjam-jam. Awalnya, produksi gudeg dilakukan dalam jumlah kecil dan dijual di sekitar lingkungan rumah. Namun karena rasa dan kualitasnya yang konsisten, warung ini semakin dikenal masyarakat. Popularitasnya terus berkembang berkat resep turun-temurun dan dedikasi keluarga dalam mempertahankan keaslian rasa gudeg kering Jogja. Seiring waktu, usaha rumahan tersebut berkembang menjadi beberapa cabang yang tersebar di Yogyakarta. Meskipun kini melayani pelanggan dalam skala besar, proses masak tradisional tetap dipertahankan. Itulah yang membuat Gudeg Yu Djum tetap menjadi ikon kuliner Jogja yang legendaris, baik bagi warga lokal maupun wisatawan.",
    details: { type: "Restoran", facilities: ["Parkir", "Toilet", "Area Makan Luas", "Mushola"] },
    tags: ["family_owned", "preserves_cultural_heritage", "locally_sourced_materials"],
    video_url: "https://www.youtube.com/embed/KokmnrwBYZQ?si=3II_yWN0EtZvc7QX&amp;controls=0",
    products: [
      { id: "p1", name: "Nasi Gudeg", price: 35000, description: "Nasi Gudeg yang disajikan lengkap dengan nasi dicampur dengan kuah santan kental (areh), ayam kampung, telur, tempe, tahu dan sambal goreng krecek. Nasi Gudeg biasanya langsung dinikmati ditempat bersama temen atau keluarga.", image_url: "https://gudegyudjum.com/storage/app/public/img/home/card___gudeg-yu-djum-jogja-kendil-kuliner-khas-jogja__63a0815050e02__80.jpg" },
      { id: "p2", name: "Gudeg Kendil ", price: 45000, description: "Gudeg Kendil adalah salah satu cara penyajian yang khas dari Gudeg. Dimana didalam kendil (kuali tanah liat) tersebut di masukkan beberapa komponen daripada Gudeg tersebut. Yaitu Gudeg (sayur nangka), Telur, Ayam, Krecek (sambal goreng kulit sapi).", image_url: "https://gudegyudjum.com/storage/app/public/img/home/card___gudeg-yu-djum-jogja-kendil-kuliner-khas-jogja__63a08190c7600__80.jpg" }
    ],
  },
  {
    id: 2,
    name: "Kopi Joss Lik Man",
    category: "Makanan",
    subcategory: "Angkringan",
    phone: "081234567890",
    priceRange: [3000, 15000],
    paymentMethods: ["Tunai", "QRIS"],
    lastUpdated: "2025-11-01",
    reviewsList: [/* ... */],
    owner: { name: "Lik Man", joined: "2024-02-10", verified: true },
    rating: 95,
    reviews: 450,
    location: "Utara Stasiun Tugu",
    distance: "5 min",
    priceFrom: 5000,
    latitude: -7.7827,
    longitude: 110.3672,
    images: [
      "https://gdb.voanews.com/509F8AB2-D0B0-4269-B9E7-B6447FC579D3_w1080_h608_b.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUgUVs__HPlytDUWWHJdzIkLw1tNxlCpLNDg&s",
      "https://www.nescafe.com/id/sites/default/files/2023-09/Proses%20Pengolahan%20Biji%20Kopi%20Sebelum%20Horizontal%20Reference%20Image.jpg",
      "https://nutracomesindotama.co.id/image/cache/catalog/Blog-images/barista-960x540.jpg",
      "https://live.staticflickr.com/3138/2778609368_2c569ae095_z.jpg"
    ],
    description: "Kopi Joss adalah salah satu minuman khas Yogyakarta yang dikenal karena keunikannya: secuil arang panas membara dicelupkan langsung ke dalam segelas kopi hitam. Minuman ini berasal dari angkringan legendaris Lik Man, yang berlokasi di kawasan Stasiun Tugu, Yogyakarta. Asal mula Kopi Joss bermula pada tahun 1980-an, ketika Lik Man, seorang pedagang angkringan generasi pertama, bereksperimen untuk memberikan sensasi berbeda pada kopi hitam yang ia jual. Ceritanya, suatu malam Lik Man melihat para pelanggan yang mengeluh sakit perut atau kembung setelah minum kopi. Menurut pengalaman tradisional Jawa, arang panas dipercaya dapat membantu meredakan gangguan pencernaan dan menetralkan zat tertentu. Dari situlah muncul ide sederhana namun unik: memasukkan arang panas langsung ke dalam gelas kopi. Ketika arang menyentuh kopi, terdengar bunyi “joss!” yang kemudian menginspirasi nama minuman tersebut: Kopi Joss. Walaupun terlihat ekstrem, proses ini tidak membuat kopi terasa gosong. Justru, arang panas membuat suhu kopi lebih stabil dan memberikan rasa yang lebih halus serta kurang asam. Keunikan ini segera menarik perhatian pengunjung lokal maupun wisatawan, dan Kopi Joss pun menjadi ikon baru dari angkringan Yogyakarta. Hari ini, Kopi Joss Lik Man dikenal sebagai pelopor kopi arang dan menjadi agenda wajib bagi wisatawan yang datang ke Jogja. Popularitasnya membuat konsep kopi arang diadaptasi oleh sejumlah angkringan lain, tetapi angkringan Lik Man tetap menjadi yang paling legendaris karena merupakan tempat asal mula minuman unik ini.",
    details: { type: "Angkringan", facilities: ["Tempat Duduk Lesehan", "Toilet Umum Terdekat"] },
    tags: ["preserves_cultural_heritage", "small_batch"],
    video_url: "https://www.youtube.com/embed/mTbxB_UtvvU?si=6KMYdEeP-p2DP1EV&amp;controls=0",
    products: [
      { id: "p1", name: "Sate Kulit", price: 3000, description: "Tambahan yang sempurna untuk hidangan utama.", image_url: "https://i.gojekapi.com/darkroom/gofood-indonesia/v2/images/uploads/8ac00ace-bddd-48a7-b1dc-d9c4e023136a_b83533f0-29fd-46e2-bcd5-a08286359d29_master-menu-item-image_1585727135664.jpg?auto=format" },
      { id: "p2", name: "Sate Usus", price: 3000, description: "Tambahan yang sempurna untuk hidangan utama.", image_url: "https://i.gojekapi.com/darkroom/gofood-indonesia/v2/images/uploads/3f4de994-f3ba-476b-87a1-2f8a6d066d98_6bacbf50-bcf5-40e3-89b2-3970232d4809_master-menu-item-image_1577084272487.jpg?auto=format" }
    ],
  },
  {
    id: 3,
    name: "Hamzah Batik Malioboro",
    category: "Belanja",
    subcategory: "Batik & Kerajinan",
    phone: "0274588524",
    priceRange: [15000, 1000000],
    paymentMethods: ["Tunai", "QRIS", "Debit", "Kartu Kredit"],
    lastUpdated: "2025-10-15",
    reviewsList: [/* ... */],
    owner: { name: "Keluarga Hamzah", joined: "2024-01-20", verified: true },
    rating: 97,
    reviews: 1200,
    location: "Jl. Malioboro No.9",
    distance: "0 min",
    priceFrom: 30000,
    latitude: -7.7949,
    longitude: 110.3659,
    images: [
      "https://hamzahbatik.co.id/wp-content/uploads/2024/07/foto-toko.jpg",
      "https://asset-2.tribunnews.com/jogja/foto/bank/originals/PROFIL-Hamzah-Sulaeman-Pengusaha-dan-Seniman-Pemilik-Raminten-Ikon-Legendaris-Wisata-Jogja.jpg",
      "https://www.jnjbatik.com/wp-content/uploads/2016/11/10-Alat-dan-Bahan-Untuk-Membuat-Batik-Tulis.jpg",
      "https://www.rinso.com/images/h0nadbhvm6m4/17RmARrAatDIJ0x2DxsGSc/68f28770f0815e43ef8408c6751dcefb/MDIuX1JpbnNvX09rdG9iZXJfSGVhZGVyLmpwZw/1000w-668h/pembatik-pemula.jpg",
      "https://down-id.img.susercontent.com/file/id-11134207-7rbka-m7w0egccli4t08@resize_w450_nl.webp"
    ],
    description: "Hamzah Batik, yang sebelumnya dikenal dengan nama Mirota Batik, didirikan pada tahun 1979 dengan konsep awal sebagai “Malioboro Baru”, sebuah pasar kecil yang terdiri dari beberapa kios atau stand. Pada masa itu, pusat keramaian kawasan Malioboro masih terpusat di sekitar toko Ramai di bagian utara, sehingga area “Malioboro Baru” masih relatif sepi pengunjung. Hamzah, pendiri usaha ini, memulai langkahnya dengan menyewa tiga stand yang menawarkan produk batik dan kerajinan tangan. Seiring berjalannya waktu, usaha tersebut mengalami perkembangan pesat, ditandai dengan bertambahnya jumlah stand yang disewa. Perkembangan ini terus berlanjut hingga akhirnya Mirota Batik tumbuh dan dikenal luas oleh masyarakat. Nama “Mirota Batik” diambil dari nama usaha milik orang tua Hamzah pada tahun 1950-an, yaitu “Mirota”, yang merupakan singkatan dari Minuman, Roti, dan Tawar. Usaha tersebut berlokasi di kawasan Kotabaru dan bergerak di bidang penjualan bahan pokok dan makanan, seperti gula, kopi, mentega, dan roti tawar. Pada tahun 2004, toko Mirota Batik mengalami musibah kebakaran di tengah tingginya jumlah pengunjung. Untuk sementara waktu, operasional toko dipindahkan ke Mirota Gallery yang terletak di Jalan Malioboro, sambil menunggu proses renovasi bangunan utama. Satu tahun kemudian, pembangunan gedung baru Hamzah Batik Malioboro selesai dengan desain tiga lantai dan luas bangunan mencapai 802 m².",
    details: { type: "Toko Oleh-oleh", facilities: ["AC", "Toilet", "Lift", "Rest Area"] },
    tags: ["locally_sourced_materials", "preserves_cultural_heritage", "empowers_women", "family_owned"],
    video_url: "https://www.youtube.com/embed/86B__OoXu1c?si=TZlgVuawreMQZguF&amp;controls=0",
    products: [
      { id: "p1", name: "Hamzah Batik - Outer Lily", price: 288000, description: "Batik paling populer dan direkomendasikan.", image_url: "https://down-id.img.susercontent.com/file/id-11134207-7rbk5-m7ll4ylwk56sa3.webp" },
      { id: "p2", name: "Hamzah Batik - Hem Seri Gallus", price: 465750, description: "Batik paling populer dan direkomendasikan.", image_url: "https://down-id.img.susercontent.com/file/id-11134207-7rbkb-m7u75ihaeobmd7.webp" }
    ],
  },
  {
    id: 4,
    name: "Pasar Beringharjo",
    category: "Belanja",
    subcategory: "Pasar Tradisional",
    phone: "0274515871",
    priceRange: [5000, 500000],
    paymentMethods: ["Tunai", "QRIS (Sebagian Tenant)"],
    lastUpdated: "2025-10-01",
    reviewsList: [/* ... */],
    owner: { name: "Pemerintah Kota Yogyakarta", joined: "2024-01-01", verified: true },
    rating: 96,
    reviews: 850,
    location: "Jl. Malioboro",
    distance: "2 min",
    priceFrom: 10000,
    latitude: -7.7984,
    longitude: 110.3662,
    images: [
      "https://jogjacagar.jogjaprov.go.id/assets/uploads/files/foto/pasar-beringharjo/35b3255cf258f2e224937897c2900a74.png",
      "https://jogjacagar.jogjaprov.go.id/assets/uploads/files/foto/pasar-beringharjo/35b3255cf258f2e224937897c2900a74.png",
      "https://www.jnjbatik.com/wp-content/uploads/2016/11/10-Alat-dan-Bahan-Untuk-Membuat-Batik-Tulis.jpg",
      "https://www.rinso.com/images/h0nadbhvm6m4/17RmARrAatDIJ0x2DxsGSc/68f28770f0815e43ef8408c6751dcefb/MDIuX1JpbnNvX09rdG9iZXJfSGVhZGVyLmpwZw/1000w-668h/pembatik-pemula.jpg",
      "https://down-id.img.susercontent.com/file/id-11134207-7rbka-m7w0egccli4t08@resize_w450_nl.webp"
    ],
    description: "Pasar Beringharjo didirikan secara formal oleh Keraton Ngayogyakarta Hadiningrat, dengan aktifitas pasar yang berjalan sejak masa Sri Sultan Hamengku Buwono I, dan kemudian dibangun secara permanen (kios/los) dengan bantuan kolonial Belanda pada 1925. Jadi “pembuat” utama adalah Keraton Yogyakarta (melalui sultan), dengan pelaksanaan pembangunan fisik oleh perusahaan beton Belanda.",
    details: { type: "Pasar Tradisional", facilities: ["Toilet Umum", "Area Parkir Luas", "ATM Center"] },
    tags: ["locally_sourced_materials", "preserves_cultural_heritage", "community_empowerment"],
    video_url: "https://www.youtube.com/embed/xsgyxe7GOWw?si=oMFOag6uGJcFSDR5&amp;controls=0",
    products: [
      { id: "p1", name: "Batik - Outer", price: 50000, description: "Batik paling populer dan direkomendasikan.", image_url: "https://down-id.img.susercontent.com/file/id-11134207-7rbk5-m7ll4ylwk56sa3.webp" },
      { id: "p2", name: "Batik - Hem", price: 45000, description: "Batik paling populer dan direkomendasikan.", image_url: "https://down-id.img.susercontent.com/file/id-11134207-7rbkb-m7u75ihaeobmd7.webp" }
    ],
  },
  {
    id: 5,
    name: "Sewa Motor Mandiri",
    category: "Jasa",
    subcategory: "Rental Kendaraan",
    phone: "085612341234",
    priceRange: [60000, 150000],
    paymentMethods: ["Tunai", "Transfer Bank"],
    lastUpdated: "2025-10-28",
    reviewsList: [/* ... */],
    owner: { name: "Pak Mandiri", joined: "2024-03-05", verified: false },
    rating: 98,
    reviews: 150,
    location: "Dekat Stasiun Lempuyangan",
    distance: "15 min",
    priceFrom: 60000,
    latitude: -7.7937,
    longitude: 110.3781,
    images: [
      "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1623871638006-e26b133c4ead?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Jasa penyewaan motor harian di Yogyakarta. ...",
    details: { type: "Rental Motor", facilities: ["Helm", "Jas Hujan", "Layanan Antar Jemput"] },
    tags: ["family_owned"],
    video_url: videoJasa,
    products: serviceProducts,
  },
  {
    id: 6,
    name: "Bakpia Pathok 25",
    category: "Produk",
    subcategory: "Oleh-oleh",
    phone: "0274567890",
    priceRange: [30000, 50000],
    paymentMethods: ["Tunai", "QRIS", "Debit"],
    lastUpdated: "2025-10-29",
    reviewsList: [/* ... */],
    owner: { name: "Keluarga Pathok 25", joined: "2024-01-12", verified: true },
    rating: 97,
    reviews: 620,
    location: "Jl. KS Tubun (Pathuk)",
    distance: "10 min",
    priceFrom: 35000,
    latitude: -7.7925,
    longitude: 110.3601,
    images: [
      "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1563805042-7684c019e1cb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Salah satu merek Bakpia Pathok paling terkenal. ...",
    details: { type: "Toko Oleh-oleh", facilities: ["Area Produksi Terbuka", "Parkir Bus", "Toilet"] },
    tags: ["family_owned", "locally_sourced_materials", "small_batch", "preserves_cultural_heritage"],
    video_url: videoMakanan,
    products: [
      { id: "p1", name: "Bakpia Kering (Isi 15)", price: 35000, description: "Varian rasa kacang hijau, keju, cokelat.", image_url: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80" },
      { id: "p2", name: "Bakpia Basah (Isi 20)", price: 45000, description: "Tahan 5 hari, rasa original kacang hijau.", image_url: "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80" }
    ],
  },
  {
    id: 7,
    name: "Jasa Tur Becak Kraton",
    category: "Jasa",
    subcategory: "Tur Wisata",
    phone: "081987654321",
    priceRange: [50000, 150000],
    paymentMethods: ["Tunai"],
    lastUpdated: "2025-10-20",
    reviewsList: [/* ... */],
    owner: { name: "Paguyuban Becak Wisata", joined: "2024-05-15", verified: false },
    rating: 94,
    reviews: 80,
    location: "Alun-Alun Utara",
    distance: "12 min",
    priceFrom: 50000,
    latitude: -7.8048,
    longitude: 110.3643,
    images: [
      "https://images.unsplash.com/photo-1555860163-30588aaa6b6b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1594480545281-c7f76b05264b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Keliling area Kraton, Tamansari, dan Wijilan menggunakan becak tradisional. ...",
    details: { type: "Jasa Tur", facilities: ["Pemandu Lokal", "Spot Foto"] },
    tags: ["preserves_cultural_heritage", "community_empowerment", "custom_orders", "locally_sourced_materials"],
    video_url: videoJasa,
    products: serviceProducts,
  },
  {
    id: 8,
    name: "Lumpia Samijaya",
    category: "Makanan",
    subcategory: "Jajanan",
    phone: "0274513938",
    priceRange: [6000, 7000],
    paymentMethods: ["Tunai", "QRIS"],
    lastUpdated: "2025-11-01",
    reviewsList: [/* ... */],
    owner: { name: "Samijaya", joined: "2024-02-18", verified: true },
    rating: 98,
    reviews: 710,
    location: "Jl. Malioboro (Depan Hotel Mutiara)",
    distance: "1 min",
    priceFrom: 6000,
    latitude: -7.7928,
    longitude: 110.3658,
    images: [
      "https://images.unsplash.com/photo-1631102914562-b53c617c5b5f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1618190920038-7698d6c75b06?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Lumpia legendaris di Malioboro. ...",
    details: { type: "Kaki Lima", facilities: ["Hanya Takeaway"] },
    tags: ["small_batch", "family_owned"],
    video_url: videoMakanan,
    products: foodProducts,
  },
  {
    id: 9,
    name: "ViaVia Artisan Bakery",
    category: "Produk",
    subcategory: "Bakery",
    phone: "0274381578",
    priceRange: [15000, 70000],
    paymentMethods: ["Tunai", "QRIS", "Debit", "Kartu Kredit"],
    lastUpdated: "2025-10-25",
    reviewsList: [/* ... */],
    owner: { name: "Mie Cornoedus", joined: "2024-03-11", verified: true },
    rating: 96,
    reviews: 230,
    location: "Prawirotaman",
    distance: "20 min",
    priceFrom: 20000,
    latitude: -7.8166,
    longitude: 110.3705,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2-efjHhSqR_0DOc1CvaxKnfn3fh9ONIcdrA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkHaWsaLF2ciFj8bgPcXn1EWhTYCgY7pukaA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST4B0rauchiMri_C0adW2HcQoHHJ-RLiWc3w&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTamQImSKYsVBbnlJDk-6Ca6UCXoCrO1genTA&s",
      "https://viaviajogja.com/wp-content/uploads/2020/06/small-baguette-600x600.jpg"
    ],
    description: "Mie Cornoedus adalah bagian dari sekelompok pemandu wisata untuk sebuah agen perjalanan Belgia yang terkenal dengan tur dan ekspedisinya yang penuh petualangan serta pendiriannya tentang pariwisata yang bertanggung jawab. Ia juga berpartisipasi dalam memberikan pelatihan kepada pemandu wisata baru dan secara rutin berkumpul untuk membahas teknik pelatihan dan filosofi perjalanan. Beberapa dari mereka memiliki ide untuk mendirikan kafe pelancong di Belgia, yang dapat mempromosikan cara pandang yang berbeda terhadap dunia melalui berbagai kegiatan. Hal ini menginspirasinya dan beberapa orang lainnya untuk berpikir lebih global dan mereka melihat konsep serupa di berbagai belahan dunia. Kafe ini dapat menjadi pusat bagi para pelancong, komunitas lokal, dan tempat untuk belajar tentang kehidupan sehari-hari kontemporer. Dengan kata lain, mereka bercita-cita menjadi tempat pertemuan lintas budaya dan menerapkan ide-ide pariwisata berkelanjutan. Ia datang ke Yogyakarta pada tahun 1995 dengan tujuan mendirikan ViaVia di sini.",
    details: { type: "Bakery", facilities: ["Kafe", "Toko Organik", "Wifi"] },
    tags: ["social_enterprise", "eco_friendly", "small_batch", "locally_sourced_materials", "empowers_women", "natural_dyes"],
    video_url: "https://www.youtube.com/embed/h2I9W2KxnZc?si=lUlkcvNrAJdvujzI&amp;controls=0",
    products: [
      { id: "p1", name: "Whole Wheat Baguette", price: 35000, description: "Whole Wheat Baguette A long, wide loaf made from local organic whole wheat, topped with a blend of black and white sesame seeds.", image_url: "https://viaviajogja.com/wp-content/uploads/2020/06/whole-wheat-baguette-600x600.jpg" },
      { id: "p2", name: "Panettone", price: 55000, description: "Panettone A classic Italian sweet bread made with sourdough starter and processed in slow long fermintation mixed with dried fruits and almond", image_url: "https://viaviajogja.com/wp-content/uploads/2024/12/Panettone-600x600.jpg" }
    ],
  },
  {
    id: 10,
    name: "Tempo Gelato Prawirotaman",
    category: "Makanan",
    subcategory: "Dessert",
    phone: "0274373272",
    priceRange: [25000, 50000],
    paymentMethods: ["Tunai", "QRIS", "Debit"],
    lastUpdated: "2025-10-30",
    reviewsList: [/* ... */],
    owner: { name: "Rudy Christian Festraets", joined: "2024-01-30", verified: true },
    rating: 98,
    reviews: 1500,
    location: "Prawirotaman",
    distance: "20 min",
    priceFrom: 25000,
    latitude: -7.817,
    longitude: 110.37,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSS_29CNF0BuMbgBj9fxrnOWZu3iO9e5r8_Lw&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSS_29CNF0BuMbgBj9fxrnOWZu3iO9e5r8_Lw&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmA7WuAhHofYIPlJvEpyaAJr9tosHPZPCing&s",
      "https://asset.kompas.com/crops/LCKAS9-tNwDS8LLtMOjocBLNjqU=/0x0:1000x667/750x500/data/photo/2020/06/11/5ee24346c170f.jpg",
      "https://tempogelato.com/gallery/ice-cream-cone-tempo-gelato.jpg"
    ],
    description: "TEMPO GELATO, merupakan outlet gelato yang berdiri di tiga tempat di Kota Jogja. Berawal dari sebuah outlet kecil Tempo Gelato Prawirotaman pada tahun 2015 dengan nuansa Industrial eropa dan sentuhan khas rural (pedesaan) Indonesia. Yang menjadikan Outlet pertama ini sebagai salah satu icon-nya Kota Jogja. Pertengahan 2019, dengan persiapan yang matang, outlet Tempo Gelato Prawirotaman akhirnya direlokasi menjadi sebuah outlet yang lebih besar dengan daya tampung yang lebih banyak. Dan tetap menjadi salah satu kebanggaan Kota Jogja. Hal ini semua bisa terwujud berkat kerja keras tim project Tempo Gelato dan juga terutama support dari pelanggan setia Tempo Gelato.",
    details: { type: "Kedai Gelato", facilities: ["AC", "Toilet", "Area Duduk Indoor & Outdoor"] },
    tags: ["family_owned", "small_batch"],
    video_url: "https://www.youtube.com/embed/PPmHep0byXg?si=aDO8C4fGxrscUsdD&amp;controls=0",
    products: [
      { id: "p1", name: "Cone", price: 35000, description: "Max 2 rasa", image_url: "https://tempogelato.com/gallery/cone-tempo-gelato.jpg" },
      { id: "p2", name: "Cup Medium", price: 5000, description: "Max 3 rasa", image_url: "https://tempogelato.com/gallery/tempo-gelato-cone.jpg" }
    ],
  },
  {
    id: 11,
    name: "Toko Buku Toga Mas",
    category: "Belanja",
    subcategory: "Toko Buku",
    phone: "0274542545",
    priceRange: [10000, 300000],
    paymentMethods: ["Tunai", "QRIS", "Debit", "Kartu Kredit"],
    lastUpdated: "2025-10-22",
    reviewsList: [/* ... */],
    owner: { name: "Toga Mas", joined: "2024-02-14", verified: true },
    rating: 95,
    reviews: 310,
    location: "Kotabaru",
    distance: "10 min",
    priceFrom: 15000,
    latitude: -7.785,
    longitude: 110.3731,
    images: [
      "https://images.unsplash.com/photo-1531988042231-E42a2b124027?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Toko buku besar dengan koleksi lengkap dan harga diskon. ...",
    details: { type: "Toko Buku", facilities: ["AC", "Area Baca", "Toilet"] },
    tags: [],
    video_url: videoJasa,
    products: shopProducts,
  },
  {
    id: 12,
    name: "Laundry Express Kiloan",
    category: "Jasa",
    subcategory: "Laundry",
    phone: "087712341234",
    priceRange: [5000, 8000],
    paymentMethods: ["Tunai", "QRIS"],
    lastUpdated: "2025-11-01",
    reviewsList: [/* ... */],
    owner: { name: "Pak Budi", joined: "2024-06-01", verified: false },
    rating: 93,
    reviews: 65,
    location: "Suryodiningratan",
    distance: "15 min",
    priceFrom: 5000,
    latitude: -7.8123,
    longitude: 110.3655,
    images: [
      "https://images.unsplash.com/photo-1593078330545-322b7f7b1f57?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1610557892470-55d7e80c0b7a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Jasa laundry kiloan cepat 1 hari jadi. ...",
    details: { type: "Laundry", facilities: ["Setrika Uap", "Layanan Antar Jemput"] },
    tags: [],
    video_url: videoJasa,
    products: serviceProducts,
  },
  {
    id: 13,
    name: "Bakmi Pak Pele",
    category: "Makanan",
    subcategory: "Bakmi Jawa",
    phone: "081812345678",
    priceRange: [20000, 30000],
    paymentMethods: ["Tunai", "QRIS"],
    lastUpdated: "2025-10-27",
    reviewsList: [/* ... */],
    owner: { name: "Pak Pele", joined: "2024-02-22", verified: true },
    rating: 96,
    reviews: 280,
    location: "Alun-Alun Utara",
    distance: "12 min",
    priceFrom: 20000,
    latitude: -7.8037,
    longitude: 110.3662,
    images: [
      "https://asset-2.tribunnews.com/surabaya/foto/bank/images/PROFIL-Warung-Bakmi-Pak-Pele-Yogyakarta-yang-Dikunjungi-Presiden-Jokowi-Milik-Mantan-Pesepak-Bola.jpg",
      "https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2023/06/03/WhatsApp-Image-2023-06-03-at-122718-2532582213.jpeg",
      "https://manunggalperkasa.co.id/wp-content/uploads/2025/06/id-11134207-7qul8-lifcrm7dseg18e.jpg",
      "https://asset.kompas.com/crops/Wp0KstNkkQLxTi9q-mmuqenZtnc=/0x2181:3360x4421/1200x800/data/photo/2021/05/24/60ab13c0b68eb.jpg",
      "https://adisutjipto-airport.co.id/frontend/uploads/defaults/cLF5dt20170314143513.jpg"
    ],
    description: "Pemilik warung, Suharjiman (70) yang lebih dikenal dengan nama Pak Pele menceritakan kisahnya kepada detikJateng. Ia mulai berjualan bakmi jawa sejak tahun 1983. Saat itu usianya baru menginjak 25 tahun. Ia mengatakan asal usul penggunaan nama Pele untuk warungnya. Pertama, karena kecintaannya akan sepak bola. Kedua, lantaran ia mengidolakan legenda sepak bola asal Brazil, Pele.",
    details: { type: "Warung Kaki Lima", facilities: ["Lesehan", "Area Makan Terbuka"] },
    tags: ["preserves_cultural_heritage", "small_batch", "family_owned"],
    video_url: "https://www.youtube.com/embed/4c_-K4_XGkI?si=IWT3anWu3SVCapig&amp;controls=0",
    products: [
      { id: "p1", name: "Bakmie Goreng Kuning", price: 20000, description: "Paling populer dan direkomendasikan.", image_url: "https://i.gojekapi.com/darkroom/gofood-indonesia/v2/images/uploads/d277d4b6-e178-49d3-aae9-433027b7faf9_c7a686e7-8950-4e70-b425-e0da83d4dc69.jpg?auto=format" },
      { id: "p2", name: "Magelangan", price: 20000, description: "Paling populer dan direkomendasikan.", image_url: "https://i.gojekapi.com/darkroom/gofood-indonesia/v2/images/uploads/942c818e-e53c-4311-9215-19d0b1a6ee28_1f27c880-c233-4036-91bb-e05e4de54def.jpg?auto=format" }
    ],
  },
  {
    id: 14,
    name: "Dagadu Djokdja",
    category: "Produk",
    subcategory: "Pakaian",
    phone: "0274512341",
    priceRange: [80000, 200000],
    paymentMethods: ["Tunai", "QRIS", "Debit", "Kartu Kredit"],
    lastUpdated: "2025-10-18",
    reviewsList: [/* ... */],
    owner: { name: "PT. Aseli Dagadu Djokdja", joined: "2024-01-10", verified: true },
    rating: 95,
    reviews: 410,
    location: "Alun-Alun Utara",
    distance: "12 min",
    priceFrom: 100000,
    latitude: -7.8041,
    longitude: 110.3653,
    images: [
      "https://img.harianjogja.com/posts/2020/10/10/1052187/dagadu.jpg",
      "https://awsimages.detik.net.id/customthumb/2011/07/19/10/dagadu.jpg?w=600&q=90",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyhVumugl0w2FYijYO6AWgVKtNfP7xcuyYKA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjzTiPahsivUFY3eCCbxQyloMXFgF7nJP0KQ&s",
      "https://dagadu.co.id/cdn/shop/files/LivePro_Black_2.jpg?v=1759550120&width=493"
    ],
    description: "PT. Aseli Dagadu berdiri tanggal 9 Januari 1994 di mana pertama kali berjualan di Mall Malioboro Yogyakarta setelah sebelumnya diawali dari beberapa kegiatan komunitas. Didirikan atau dimotori oleh mahasiswa dan alumni mahasiswa teknik arsitektur UGM yang mempunyai minat yang sama tentang kepariwisataan dan perkotaan. Dua puluh lima orang yang sering berkumpul dalam suatu kegiatan waktu itu bersama-sama mendirikan PT. Aseli Dagadu. Minat terhadap bidang kepariwisataan dan perkotaan, kesukaan desain grafis khususnya kaos, diskusi tentang teori dan realitas yang kerap dilakukan merupakan faktor internal pendorong didirikannya PT. Aseli Dagadu. Dari sisi eksternal, adanya penawaran untuk berjualan di mall malioboro menjadi sebuah kesempatan menjual kaos. Kaos menjadi pilihan karena produk inilah yang paling familiar dengan mereka saat itu.",
    details: { type: "Toko Pakaian", facilities: ["AC", "Kamar Pas", "Desain Toko Unik"] },
    tags: ["preserves_cultural_heritage", "locally_sourced_materials"],
    video_url: "https://www.youtube.com/embed/UUOVcjKFrio?si=CQVpr29r6cOPYVSx&amp;controls=0",
    products: [
      { id: "p1", name: "Bakmie Goreng Kuning", price: 170000, description: "ilutrasi tentang Kerja Keras Bagai Kuda! Tanpa mengenal lelah dan menyerah. Gawa gambar wayang bertujuan agat tetap ada unsur klasik dalam desainnya. ", image_url: "https://dagadu.co.id/cdn/shop/files/2580-kuda_navy_brown_lp__2.jpg?v=1760327295&width=493" },
      { id: "p2", name: "Dagadu Kaos Boxy Suradira Jayaningrat Lebur Dening Pangastuti - Navy", price: 190000, description: "Konsep ini diambil dari sebuah filosofi Jawa yang mengajarkan bahwa segala sifat keras hati, angkara murka, dan keberanian yang sombong dapat dikalahkan atau dihancurkan oleh kebijaksanaan, kelembutan, dan kesabaran Pesannya adalah tentang bagaimana kekuatan sejati bukanlah terletak pada kekerasan atau kesombongan, melainkan pada kelembutan dan kebajikan.", image_url: "https://dagadu.co.id/cdn/shop/files/2577-macan_navy__4.jpg?v=1760349642&width=493" }
    ],
  },
  {
    id: 15,
    name: "Sate Kere Mbah Suwarni",
    category: "Makanan",
    subcategory: "Sate",
    phone: "081512341234",
    priceRange: [15000, 25000],
    paymentMethods: ["Tunai"],
    lastUpdated: "2025-10-24",
    reviewsList: [/* ... */],
    owner: { name: "Mbah Suwarni", joined: "2024-04-10", verified: false },
    rating: 94,
    reviews: 190,
    location: "Jl. Godean (Dekat Pasar Telo)",
    distance: "15 min",
    priceFrom: 15000,
    latitude: -7.791,
    longitude: 110.358,
    images: [
      "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1603052210283-a989f661fb3a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Sate 'kere' (terbuat dari gajih/lemak sapi)...",
    details: { type: "Warung Tenda", facilities: ["Lesehan"] },
    tags: ["female_founded", "small_batch", "preserves_cultural_heritage", "family_owned"],
    video_url: videoMakanan,
    products: foodProducts,
  },
  {
    id: 16,
    name: "Cokelat Monggo",
    category: "Produk",
    subcategory: "Cokelat",
    phone: "0274373192",
    priceRange: [20000, 100000],
    paymentMethods: ["Tunai", "QRIS", "Debit", "Kartu Kredit"],
    lastUpdated: "2025-10-26",
    reviewsList: [/* ... */],
    owner: { name: "Thierry Detournay", joined: "2024-02-17", verified: true },
    rating: 97,
    reviews: 300,
    location: "Tugu",
    distance: "5 min",
    priceFrom: 25000,
    latitude: -7.7818,
    longitude: 110.367,
    images: [
      "https://awsimages.detik.net.id/community/media/visual/2023/11/17/chocolate-monggo-3_169.jpeg?w=1200",
      "https://asset-2.tribunnews.com/jogja/foto/bank/images/wawancara-eksklusif-pendiri-cokelat-monggo-thierry-detournay-kenalkan-cokelat-yang-berkualitas.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAGyw4UIUBj_mfBjiagotKO7P2ddRH4Qdk-w&s",
      "https://chocolatemonggo.com/wp-content/uploads/2023/06/8.-Pembuatan-Adonan-Isian-Pelumeran-Coklat-Filling-Preparation-Melting.jpg",
      "https://chocolatemonggo.com/wp-content/uploads/2022/11/Chocolate-Monggo-Praline-Bar-Dark-Cokelat-Hitam-58-Coklat.jpg"
    ],
    description: "Thierry Detournay adalah seorang backpacker kewarganegaraan Belgia yang pada tahun 2001 silam menginjakkan kaki di Jogja. Ia seorang penyuka coklat. Ketika mencicipi coklat di Jogja, ia merasa kecewa karena coklat di negara ini terasa sangat manis, berbeda dengan coklat di negaranya, Belgia yang mempunyai rasa agak pahit. Dari situ, Thierry mencoba membuat sendiri coklat yang sesuai dengan seleranya. Dalam proses perjalanannya, Thierry bertemu dengan Edward Riando Picasauw, mahasiwa asal Maluku. Pertemuan kedua pria tersebut menghasilkan sebuah kerja sama dan pada tahun 2005 lahirlah Cokelat Monggo. Kata Monggo dipilih karena kata ini sangat familiar dan tipikal Jogja. Sebuah kata yang mudah diingat, didengar, dan unik. Monggo dalam bahasa Jawa berarti “silahkan” yang selalu digunakan oleh orang – orang Jogja/Jawa sambil mengacungkan ibu jari, ataupun ketika kita lewat di depan orang, serta pada saat kita mengundang orang masuk ke rumah atau meninggalkan rumah seseorang. Mulai dari awal proses Cokelat Monggo berdiri hingga sudah terkenal di berbagai daerah seperti sekarang ini, pembuatan dan produksi cokelat ini berada di Jogja dan menjadikan Thierry dijuluki sebagai pembuat cokelat pertama di Jogja. Pada awal mulanya proses produksi cokelat ini berada di daerah UGM. Karena berkembang semakin pesat dan menjadi sebuah industri yang membutuhkan tempat yang besar dan luas maka produksi dipindahkan ke Kotagede. Selain pabrik, di Kotagede ini juga terdapat showroom penjualan Cokelat Monggo.",
    details: { type: "Toko Cokelat", facilities: ["AC", "Tester Produk", "Kafe Kecil"] },
    tags: ["locally_sourced_materials", "small_batch", "eco_friendly", "social_enterprise", "preserves_cultural_heritage"],
    video_url: "https://www.youtube.com/embed/6_QEx0KsRmk?si=_oMJrBP-rQ91Vm6L&amp;controls=0",
    products: [
      { id: "p1", name: "MILK CHOCOLATE 41% Of Cocoa - Bar 40g", price: 30000, description: "41% cocoa Milk chocolate bar, with a creamy texture, and a strong milky taste. This dark milk chocolate with a high percentage of cocoa is made with mild cocoa beans from West Indonesia. Their rounded taste makes it a better match with milk. Filled with calcium, this is a beneficial snack for your children’s growing bones.", image_url: "https://chocolatemonggo.com/wp-content/uploads/2022/11/Chocolate-Monggo-Bar-Milk-Cokelat-Susu-41-Coklat.jpg.webp" },
      { id: "p2", name: "PRALINES BOX BALLOTIN 6pcs", price: 85000, description: "Are you looking for a sweet treat to indulge in or a gift to delight your loved ones? Look no further than our Pralines Box Ballotin from Chocolate Monggo. This delectable box features 6 pieces of expertly handcrafted pralines, each one a true work of art. Our pralines ballotin are made with the finest quality ingredients and the utmost care. We take pride in creating each piece to perfection, from the rich and creamy chocolate coating to the velvety smooth ganache filling. Every bite is a heavenly experience, with flavors that range from classic dark chocolate to nice fruits and nuts. Whether you're treating yourself or someone special, our Pralines Box Ballotin is a perfect choice. It's beautifully presented in an elegant ballotin box, making it a lovely gift for any occasion.", image_url: "https://chocolatemonggo.com/wp-content/uploads/2023/04/Chocolate-Monggo-Pralines-Box-Ballotine-6pcs.jpg.webp" }
    ],
  },
  {
    id: 17,
    name: "Studio Foto Java",
    category: "Jasa",
    subcategory: "Fotografi",
    phone: "0274512312",
    priceRange: [100000, 500000],
    paymentMethods: ["Tunai", "QRIS", "Transfer Bank"],
    lastUpdated: "2025-10-23",
    reviewsList: [/* ... */],
    owner: { name: "Java Foto", joined: "2024-03-20", verified: true },
    rating: 95,
    reviews: 110,
    location: "Kotabaru",
    distance: "10 min",
    priceFrom: 150000,
    latitude: -7.7845,
    longitude: 110.375,
    images: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1600096194534-960fada6207f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Jasa foto studio profesional dan foto wisuda. ...",
    details: { type: "Studio Foto", facilities: ["Studio AC", "Properti Foto", "Ruang Ganti"] },
    tags: ["family_owned"],
    video_url: videoJasa,
    products: serviceProducts,
  },
  {
    id: 18,
    name: "Nasi Pecel SGPC Bu Wiryo",
    category: "Makanan",
    subcategory: "Pecel",
    phone: "0274514222",
    priceRange: [15000, 25000],
    paymentMethods: ["Tunai", "QRIS"],
    lastUpdated: "2025-10-28",
    reviewsList: [/* ... */],
    owner: { name: "Keluarga Bu Wiryo", joined: "2024-02-01", verified: true },
    rating: 96,
    reviews: 400,
    location: "Kotabaru",
    distance: "10 min",
    priceFrom: 18000,
    latitude: -7.7831,
    longitude: 110.3725,
    images: [
      "https://images.unsplash.com/photo-1562635446-56063659250a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1628102322441-21c9b6f8c37c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Nasi pecel legendaris yang sudah ada sejak puluhan tahun lalu. ...",
    details: { type: "Warung Makan", facilities: ["Area Makan Luas", "Parkir"] },
    tags: ["family_owned", "preserves_cultural_heritage", "female_founded"],
    video_url: videoMakanan,
    products: foodProducts,
  },
  {
    id: 19,
    name: "Toko Progo",
    category: "Belanja",
    subcategory: "Grosir",
    phone: "0274515285",
    priceRange: [1000, 1000000],
    paymentMethods: ["Tunai", "QRIS", "Debit", "Kartu Kredit"],
    lastUpdated: "2025-10-15",
    reviewsList: [/* ... */],
    owner: { name: "Progo Group", joined: "2024-01-25", verified: true },
    rating: 93,
    reviews: 350,
    location: "Pusat Kota",
    distance: "5 min",
    priceFrom: 5000,
    latitude: -7.7963,
    longitude: 110.3695,
    images: [
      "https://images.unsplash.com/photo-1580992734408-b47c0c2c2f6d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1542838132-92c53300491e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Supermarket grosir yang menjual segala kebutuhan rumah tangga...",
    details: { type: "Grosir", facilities: ["Parkir Luas", "Food Court", "Toilet"] },
    tags: ["family_owned"],
    video_url: videoJasa,
    products: shopProducts,
  },
  {
    id: 20,
    name: "Jamu Gendong Mbah Waginem",
    category: "Produk",
    subcategory: "Herbal",
    phone: "081112341234",
    priceRange: [3000, 10000],
    paymentMethods: ["Tunai"],
    lastUpdated: "2025-11-01",
    reviewsList: [/* ... */],
    owner: { name: "Mbah Waginem", joined: "2024-07-01", verified: false },
    rating: 98,
    reviews: 75,
    location: "Pasar Kranggan",
    distance: "5 min",
    priceFrom: 5000,
    latitude: -7.7844,
    longitude: 110.3668,
    images: [
      "https://images.unsplash.com/photo-1620921282046-e179e0a16c88?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1552392372-d591060b3780?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Penjual jamu gendong tradisional dengan ramuan otentik...",
    details: { type: "Kaki Lima", facilities: ["Minum di tempat", "Bawa Pulang"] },
    tags: ["fully_handmade", "natural_dyes", "female_founded", "preserves_cultural_heritage", "locally_sourced_materials", "empowers_women", "small_batch"],
    video_url: videoKerajinan,
    products: shopProducts,
  },
  {
    id: 21,
    name: "Soto Kadipiro",
    category: "Makanan",
    subcategory: "Soto",
    phone: "0274373192",
    priceRange: [12000, 25000],
    paymentMethods: ["Tunai", "QRIS"],
    lastUpdated: "2025-10-29",
    reviewsList: [/* ... */],
    owner: { name: "Keluarga Kadipiro", joined: "2024-02-05", verified: true },
    rating: 97,
    reviews: 550,
    location: "Jl. Wates",
    distance: "20 min",
    priceFrom: 15000,
    latitude: -7.8015,
    longitude: 110.3534,
    images: [
      "https://images.unsplash.com/photo-1587324438345-e8720c0c66fe?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1604251759491-3046f3378174?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Soto ayam kampung legendaris dengan kuah bening...",
    details: { type: "Restoran", facilities: ["Parkir Luas", "Toilet", "Tempat Duduk Banyak"] },
    tags: ["family_owned", "preserves_cultural_heritage"],
    video_url: videoMakanan,
    products: foodProducts,
  },
  {
    id: 22,
    name: "Toko Perak Ansor",
    category: "Belanja",
    subcategory: "Kerajinan Perak",
    phone: "0274375107",
    priceRange: [50000, 5000000],
    paymentMethods: ["Tunai", "QRIS", "Debit", "Kartu Kredit"],
    lastUpdated: "2025-10-21",
    reviewsList: [/* ... */],
    owner: { name: "Ansor Silver", joined: "2024-03-15", verified: true },
    rating: 96,
    reviews: 180,
    location: "Kotagede",
    distance: "25 min",
    priceFrom: 100000,
    latitude: -7.8282,
    longitude: 110.392,
    images: [
      "https://images.unsplash.com/photo-1611195325838-68811f267a57?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1611956414163-0c464b19c23f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1606802236881-b7de9c6a0b99?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80"
    ],
    description: "Pusat kerajinan perak di Kotagede. ...",
    details: { type: "Toko Kerajinan", facilities: ["Workshop", "Showroom AC", "Parkir"] },
    tags: ["hand_carved", "fully_handmade", "family_owned", "preserves_cultural_heritage", "small_batch", "made_to_order", "custom_orders"],
    video_url: videoKerajinan,
    products: [
      { id: "p1", name: "Cincin Perak Filigri", price: 350000, description: "Cincin perak murni dengan ukiran filigri.", image_url: "https://images.unsplash.com/photo-1611195325838-68811f267a57?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80" },
      { id: "p2", name: "Kalung Perak", price: 700000, description: "Kalung dengan liontin perak bakar.", image_url: "https://images.unsplash.com/photo-1611956414163-0c464b19c23f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80" },
      { id: "p3", name: "Anting Perak", price: 250000, description: "Anting-anting model subang.", image_url: "https://images.unsplash.com/photo-1606802236881-b7de9c6a0b99?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80" }
    ],
  },
  {
    id: 23,
    name: "Pijat Refleksi Sehat",
    category: "Jasa",
    subcategory: "Kebugaran",
    phone: "088812341234",
    priceRange: [60000, 150000],
    paymentMethods: ["Tunai", "QRIS", "Debit"],
    lastUpdated: "2025-10-27",
    reviewsList: [/* ... */],
    owner: { name: "Pak Sehat", joined: "2024-05-10", verified: false },
    rating: 94,
    reviews: 90,
    location: "Jl. Kaliurang (Bawah)",
    distance: "15 min",
    priceFrom: 75000,
    latitude: -7.778,
    longitude: 110.3755,
    images: [
      "https://images.unsplash.com/photo-1515377905703-c4788e51af15?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1617936132034-c3b8813d6404?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Jasa pijat refleksi dan pijat tradisional untuk kebugaran. ...",
    details: { type: "Jasa Kebugaran", facilities: ["Ruangan AC", "Terapis Profesional", "Minuman Jahe"] },
    tags: ["family_owned"],
    video_url: videoJasa,
    products: serviceProducts,
  },
  {
    id: 24,
    name: "Oseng Mercon Bu Narti",
    category: "Makanan",
    subcategory: "Pedas",
    phone: "081312341234",
    priceRange: [25000, 40000],
    paymentMethods: ["Tunai", "QRIS"],
    lastUpdated: "2025-10-29",
    reviewsList: [/* ... */],
    owner: { name: "Bu Narti", joined: "2024-03-01", verified: true },
    rating: 95,
    reviews: 600,
    location: "Jl. KH. Ahmad Dahlan",
    distance: "10 min",
    priceFrom: 25000,
    latitude: -7.8011,
    longitude: 110.362,
    images: [
      "https://images.unsplash.com/photo-1572695211072-a43b2323e05a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1604251759491-3046f3378174?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Pelopor oseng-oseng super pedas (mercon) di Yogyakarta. ...",
    details: { type: "Warung Tenda", facilities: ["Lesehan", "Minuman Dingin"] },
    tags: ["female_founded", "preserves_cultural_heritage", "small_batch", "family_owned"],
    video_url: videoMakanan,
    products: foodProducts,
  },
  {
    id: 25,
    name: "Jejamuran",
    category: "Makanan",
    subcategory: "Restoran Unik",
    phone: "0274868172",
    priceRange: [15000, 40000],
    paymentMethods: ["Tunai", "QRIS", "Debit"],
    lastUpdated: "2025-10-25",
    reviewsList: [/* ... */],
    owner: { name: "Jejamuran", joined: "2024-02-28", verified: true },
    rating: 97,
    reviews: 700,
    location: "Jl. Magelang (Agak Utara)",
    distance: "30 min",
    priceFrom: 20000,
    latitude: -7.731,
    longitude: 110.3582,
    images: [
      "https://images.unsplash.com/photo-1576686001018-30640f0c0211?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1600185810766-9d3e7e311c9e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Restoran unik dengan semua menu terbuat dari jamur. ...",
    details: { type: "Restoran", facilities: ["Parkir Luas", "Toko Oleh-oleh Jamur", "Mushola"] },
    tags: ["locally_sourced_materials", "small_batch", "family_owned"],
    video_url: videoMakanan,
    products: foodProducts,
  },
  {
    id: 26,
    name: "Toko Mebel Rotan",
    category: "Produk",
    subcategory: "Mebel",
    phone: "081612341234",
    priceRange: [100000, 2000000],
    paymentMethods: ["Tunai", "Transfer Bank"],
    lastUpdated: "2025-10-19",
    reviewsList: [/* ... */],
    owner: { name: "Pak Rotan", joined: "2024-06-11", verified: false },
    rating: 94,
    reviews: 50,
    location: "Jl. Prawirotaman",
    distance: "20 min",
    priceFrom: 150000,
    latitude: -7.8175,
    longitude: 110.371,
    images: [
      "https://images.unsplash.com/photo-1594026112273-091a079f6b3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1618220790829-c88f71a0636f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1567900000780-1634f1954f92?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
      "https://images.unsplash.com/photo-1569048788106-f608a0b06431?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
      "https://images.unsplash.com/photo-1618335431302-09d6688b1f55?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
      "https://images.unsplash.com/photo-1542157798-9369c0c326c9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
    ],
    description: "Pusat kerajinan mebel dan dekorasi rumah berbahan dasar rotan. ...",
    details: { type: "Toko Mebel", facilities: ["Workshop", "Showroom"] },
    tags: ["fully_handmade", "locally_sourced_materials", "hand_woven", "custom_orders", "family_owned"],
    video_url: videoKerajinan,
    products: [
      { id: "p1", name: "Tas Rotan Dayak", price: 450000, description: "Tas jinjing klasik tenunan tangan.", image_url: "https://images.unsplash.com/photo-1567900000780-1634f1954f92?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" },
      { id: "p2", name: "Keranjang Tenun \"Setia\"", price: 320000, description: "Sempurna untuk penyimpanan di rumah.", image_url: "https://images.unsplash.com/photo-1569048788106-f608a0b06431?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" },
      { id: "p3", name: "Tatakan Rotan (Set 4)", price: 280000, description: "Estetika makan yang alami.", image_url: "https://images.unsplash.com/photo-1618335431302-09d6688b1f55?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" },
      { id: "p4", name: "Hiasan Dinding \"Matahari\"", price: 510000, description: "Cermin dinding buatan tangan.", image_url: "https://images.unsplash.com/photo-1542157798-9369c0c326c9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" }
    ],
  },
  {
    id: 27,
    name: "Cuci Sepatu Express",
    category: "Jasa",
    subcategory: "Cuci Sepatu",
    phone: "085712341234",
    priceRange: [30000, 100000],
    paymentMethods: ["Tunai", "QRIS"],
    lastUpdated: "2025-10-30",
    reviewsList: [/* ... */],
    owner: { name: "Mas Clean", joined: "2024-04-12", verified: false },
    rating: 96,
    reviews: 120,
    location: "Kotabaru",
    distance: "10 min",
    priceFrom: 30000,
    latitude: -7.786,
    longitude: 110.3745,
    images: [
      "https://images.unsplash.com/photo-1551107696-a3b472d0b586?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1608231387042-66d18ab3437a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Jasa cuci sepatu (sneakers, kanvas, kulit) profesional. ...",
    details: { type: "Jasa Cuci", facilities: ["Cuci Cepat", "Repaint", "Unyellowing"] },
    tags: [],
    video_url: videoJasa,
    products: serviceProducts,
  },
  {
    id: 28,
    name: "Toko Oleh-Oleh Raminten",
    category: "Belanja",
    subcategory: "Oleh-oleh",
    phone: "0274512345",
    priceRange: [5000, 100000],
    paymentMethods: ["Tunai", "QRIS", "Debit"],
    lastUpdated: "2025-10-26",
    reviewsList: [/* ... */],
    owner: { name: "Keluarga Hamzah", joined: "2024-02-19", verified: true },
    rating: 95,
    reviews: 250,
    location: "Kotabaru",
    distance: "10 min",
    priceFrom: 10000,
    latitude: -7.7839,
    longitude: 110.372,
    images: [
      "https://olaholehraminten.co.id/wp-content/uploads/2025/04/2-2.webp",
      "https://asset-2.tribunnews.com/jogja/foto/bank/originals/PROFIL-Hamzah-Sulaeman-Pengusaha-dan-Seniman-Pemilik-Raminten-Ikon-Legendaris-Wisata-Jogja.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEdbJNCg4LB5EF7_jPC-jqrHQ_jzo85ejvQQ&s",
      "https://static.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/p1/775/2024/07/18/bakpia-jogkem-831870113.jpeg",
      "https://hamzahbatik.co.id/wp-content/uploads/2024/02/8408f137e7230f525fb146eb540538c7d338a5ae_s2_n2_y2.jpg"
    ],
    description: "lah-oleh Raminten adalah salah satu pusat oleh-oleh terbaru di Yogyakarta, yang terletak di Kampung Wisata Ngampilan. Resmi dibuka pada 21 Desember 2024, tempat ini menjadi alternatif baru bagi para wisatawan yang ingin mencari oleh-oleh khas Jogja. Uniknya, Olah-oleh Raminten buka 24 jam setiap hari, jadi cocok banget untuk pengunjung yang datang siang, malam, bahkan dini hari. Konsep tempat ini tetap membawa nuansa budaya Jawa, sejalan dengan lini usaha Raminten lainnya.",
    details: { type: "Toko Oleh-oleh", facilities: ["AC", "Parkir"] },
    tags: ["family_owned", "preserves_cultural_heritage", "female_founded"],
    video_url: "https://www.youtube.com/embed/Sqyd2r_xdJk?si=B3yKhlC94R-yBxVx&amp;controls=0",
    products: [
      { id: "p1", name: "Bakpia", price: 50000, description: "Bakpia Premium Raminten Rasa Coklat", image_url: "https://olaholehraminten.co.id/wp-content/uploads/2025/04/Bakpia-Premium-Coklat-Raminten-upl.webp" },
      { id: "p2", name: "Keripik", price: 70000, description: "Keripik Sale Pisang Raminten", image_url: "https://olaholehraminten.co.id/wp-content/uploads/2025/04/Keripik-Sale-Pisang-upl.webp" }
    ],
  },
  {
    id: 29,
    name: "Wedang Ronde Mbah Payem",
    category: "Makanan",
    subcategory: "Minuman",
    phone: "081412341234",
    priceRange: [8000, 10000],
    paymentMethods: ["Tunai"],
    lastUpdated: "2025-10-27",
    reviewsList: [/* ... */],
    owner: { name: "Mbah Payem", joined: "2024-03-12", verified: false },
    rating: 97,
    reviews: 200,
    location: "Jl. Kauman",
    distance: "10 min",
    priceFrom: 8000,
    latitude: -7.803,
    longitude: 110.364,
    images: [
      "https://images.unsplash.com/photo-1588785292021-d7f02d515a40?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1630440533342-6031d7e296a1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Wedang Ronde legendaris yang menjadi langganan Sultan. ...",
    details: { type: "Kaki Lima", facilities: ["Lesehan"] },
    tags: ["female_founded", "preserves_cultural_heritage", "small_batch", "family_owned"],
    video_url: videoMakanan,
    products: foodProducts,
  },
  {
    id: 30,
    name: "Jasa Lukis Wajah Malioboro",
    category: "Jasa",
    subcategory: "Seni",
    phone: "081712341234",
    priceRange: [50000, 200000],
    paymentMethods: ["Tunai", "QRIS"],
    lastUpdated: "2025-10-20",
    reviewsList: [/* ... */],
    owner: { name: "Komunitas Pelukis", joined: "2024-07-07", verified: false },
    rating: 93,
    reviews: 60,
    location: "Jl. Malioboro",
    distance: "0 min",
    priceFrom: 100000,
    latitude: -7.7935,
    longitude: 110.3655,
    images: [
      "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1482160549825-59ac1b23cb6e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Para seniman jalanan yang menawarkan jasa lukis sketsa wajah cepat...",
    details: { type: "Jasa Seni", facilities: ["Lukis di Tempat", "Bisa Pesan"] },
    tags: ["fully_handmade", "made_to_order", "personalizable", "custom_orders", "community_empowerment"],
    video_url: videoKerajinan,
    products: serviceProducts,
  },
  {
    id: 31,
    name: "Kerajinan Kulit Asli",
    category: "Produk",
    subcategory: "Kerajinan Kulit",
    phone: "081222333444",
    priceRange: [50000, 500000],
    paymentMethods: ["Tunai", "QRIS", "Debit"],
    lastUpdated: "2025-10-22",
    reviewsList: [/* ... */],
    owner: { name: "Pak Kulit", joined: "2024-04-18", verified: false },
    rating: 95,
    reviews: 110,
    location: "Jl. Malioboro",
    distance: "1 min",
    priceFrom: 70000,
    latitude: -7.794,
    longitude: 110.3657,
    images: [
      "https://images.unsplash.com/photo-1605812863642-19e98b0a96b4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1524580323223-a589077271b6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Toko yang menjual berbagai produk kerajinan kulit asli...",
    details: { type: "Toko Kerajinan", facilities: ["Bisa Custom", "Showroom"] },
    tags: ["fully_handmade", "small_batch", "locally_sourced_materials", "personalizable", "custom_orders"],
    video_url: videoKerajinan,
    products: [
      { id: "p1", name: "Dompet Kulit Pria", price: 150000, description: "Dompet kulit sapi asli jahitan tangan.", image_url: "https://images.unsplash.com/photo-1605812863642-19e98b0a96b4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80" },
      { id: "p2", name: "Ikat Pinggang Kulit", price: 250000, description: "Ikat pinggang kulit sapi dengan kepala kuningan.", image_url: "https://images.unsplash.com/photo-1524580323223-a589077271b6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80" }
    ],
  },
  {
    id: 32,
    name: "Rujak Es Krim Pak Nardi",
    category: "Makanan",
    subcategory: "Dessert",
    phone: "081333444555",
    priceRange: [10000, 15000],
    paymentMethods: ["Tunai", "QRIS"],
    lastUpdated: "2025-10-28",
    reviewsList: [/* ... */],
    owner: { name: "Pak Nardi", joined: "2024-03-25", verified: false },
    rating: 96,
    reviews: 210,
    location: "Pakualaman",
    distance: "15 min",
    priceFrom: 10000,
    latitude: -7.8018,
    longitude: 110.375,
    images: [
      "https://images.unsplash.com/photo-1615478503195-039c4c70b8f0?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1579954115545-a95591f28bfc?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Kombinasi unik rujak buah segar dengan es krim puter...",
    details: { type: "Kaki Lima", facilities: ["Area Duduk Terbatas"] },
    tags: ["small_batch", "family_owned"],
    video_url: videoMakanan,
    products: foodProducts,
  },
  {
    id: 33,
    name: "Toko Mas Kranggan",
    category: "Belanja",
    subcategory: "Perhiasan",
    phone: "0274512121",
    priceRange: [300000, 10000000],
    paymentMethods: ["Tunai", "Debit", "Transfer Bank"],
    lastUpdated: "2025-10-23",
    reviewsList: [/* ... */],
    owner: { name: "Keluarga Kranggan", joined: "2024-02-11", verified: true },
    rating: 94,
    reviews: 85,
    location: "Pasar Kranggan",
    distance: "5 min",
    priceFrom: 500000,
    latitude: -7.7842,
    longitude: 110.3665,
    images: [
      "https://images.unsplash.com/photo-1606802236881-b7de9c6a0b99?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1611860363533-8ade5f4d88a4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Toko perhiasan emas dengan model lengkap dan harga bersaing. ...",
    details: { type: "Toko Perhiasan", facilities: ["Terima Jual Beli", "Sertifikat"] },
    tags: ["family_owned"],
    video_url: videoKerajinan,
    products: shopProducts,
  },
  {
    id: 34,
    name: "Servis Laptop Cepat",
    category: "Jasa",
    subcategory: "Servis Elektronik",
    phone: "089912341234",
    priceRange: [50000, 500000],
    paymentMethods: ["Tunai", "QRIS", "Transfer Bank"],
    lastUpdated: "2025-10-29",
    reviewsList: [/* ... */],
    owner: { name: "Mas Tekno", joined: "2024-05-01", verified: false },
    rating: 95,
    reviews: 130,
    location: "Jl. Godean (Dekat Kota)",
    distance: "15 min",
    priceFrom: 50000,
    latitude: -7.7895,
    longitude: 110.355,
    images: [
      "https://images.unsplash.com/photo-1587573089734-09cb69c0f11a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Jasa perbaikan laptop, instal ulang, dan upgrade hardware. ...",
    details: { type: "Servis Elektronik", facilities: ["Gratis Cek Kerusakan", "Garansi Servis"] },
    tags: [],
    video_url: videoJasa,
    products: serviceProducts,
  },
  {
    id: 35,
    name: "Gudeg Pawon",
    category: "Makanan",
    subcategory: "Gudeg Tradisional",
    phone: "081212345678",
    priceRange: [20000, 35000],
    paymentMethods: ["Tunai"],
    lastUpdated: "2025-10-26",
    reviewsList: [/* ... */],
    owner: { name: "Keluarga Gudeg Pawon", joined: "2024-03-10", verified: true },
    rating: 98,
    reviews: 650,
    location: "Dekat UTY Glagahsari",
    distance: "20 min",
    priceFrom: 20000,
    latitude: -7.8105,
    longitude: 110.3845,
    images: [
      "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?ixlib=rb-4.0.3&auto=format&fit=crop&w=1981&q=80",
    ],
    description: "Pengalaman unik makan gudeg otentik langsung dari 'pawon' (dapur). ...",
    details: { type: "Warung Makan", facilities: ["Suasana Tradisional", "Antri"] },
    tags: ["family_owned", "preserves_cultural_heritage", "small_batch", "locally_sourced_materials"],
    video_url: videoMakanan,
    products: foodProducts,
  },
  {
    id: 36,
    name: "Toko Kain Kiloan",
    category: "Belanja",
    subcategory: "Kain",
    phone: "0274371234",
    priceRange: [20000, 100000],
    paymentMethods: ["Tunai", "Debit"],
    lastUpdated: "2025-10-17",
    reviewsList: [/* ... */],
    owner: { name: "Toko Kain", joined: "2024-04-20", verified: false },
    rating: 93,
    reviews: 70,
    location: "Jl. Bantul (Bawah)",
    distance: "20 min",
    priceFrom: 25000,
    latitude: -7.82,
    longitude: 110.36,
    images: [
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Menjual berbagai macam kain sisa garmen secara kiloan. ...",
    details: { type: "Toko Kain", facilities: ["Banyak Pilihan", "Parkir"] },
    tags: [],
    video_url: videoKerajinan,
    products: shopProducts,
  },
  {
    id: 37,
    name: "Perlengkapan Jahit Benang Emas",
    category: "Produk",
    subcategory: "Alat Jahit",
    phone: "0274511222",
    priceRange: [1000, 50000],
    paymentMethods: ["Tunai", "QRIS"],
    lastUpdated: "2025-10-24",
    reviewsList: [/* ... */],
    owner: { name: "Benang Emas", joined: "2024-03-18", verified: false },
    rating: 94,
    reviews: 45,
    location: "Dekat Pasar Beringharjo",
    distance: "3 min",
    priceFrom: 2000,
    latitude: -7.7988,
    longitude: 110.367,
    images: [
      "https://images.unsplash.com/photo-1517694466633-f7d7c6f0e4b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1599723002633-87f583095034?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Toko kecil yang menjual segala kebutuhan menjahit. ...",
    details: { type: "Toko Alat Jahit", facilities: ["Lengkap"] },
    tags: ["family_owned"],
    video_url: videoKerajinan,
    products: shopProducts,
  },
  {
    id: 38,
    name: "House of Raminten",
    category: "Makanan",
    subcategory: "Restoran Unik",
    phone: "0274547315",
    priceRange: [5000, 40000],
    paymentMethods: ["Tunai", "QRIS", "Debit"],
    lastUpdated: "2025-10-29",
    reviewsList: [/* ... */],
    owner: { name: "Raminten Group", joined: "2024-02-19", verified: true },
    rating: 96,
    reviews: 1100,
    location: "Kotabaru",
    distance: "10 min",
    priceFrom: 15000,
    latitude: -7.784,
    longitude: 110.3722,
    images: [
      "https://images.unsplash.com/photo-1549488344-1f9b8d243a93?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1514933651103-005eec06c04b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Restoran dengan konsep Jawa yang sangat kental. ...",
    details: { type: "Restoran", facilities: ["Suasana Unik", "Toilet", "Spot Foto", "Buka 24 Jam (TBC)"] },
    tags: ["family_owned", "preserves_cultural_heritage", "female_founded"],
    video_url: videoMakanan,
    products: foodProducts,
  },
  {
    id: 39,
    name: "Penjahit Jas Rapi",
    category: "Jasa",
    subcategory: "Tailor",
    phone: "081111222333",
    priceRange: [800000, 3000000],
    paymentMethods: ["Tunai", "Transfer Bank"],
    lastUpdated: "2025-10-21",
    reviewsList: [/* ... */],
    owner: { name: "Pak Rapi", joined: "2024-04-14", verified: false },
    rating: 97,
    reviews: 80,
    location: "Jl. C. Simanjuntak",
    distance: "15 min",
    priceFrom: 1000000,
    latitude: -7.7788,
    longitude: 110.3721,
    images: [
      "https://images.unsplash.com/photo-1593030103057-01a40b99176f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1497032628192-86f99079de7c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Jasa jahit (tailor) khusus jas pria. ...",
    details: { type: "Tailor", facilities: ["Pengukuran di Tempat", "Pilihan Kain"] },
    tags: ["made_to_order", "custom_orders", "fully_handmade", "family_owned"],
    video_url: videoKerajinan,
    products: serviceProducts,
  },
  {
    id: 40,
    name: "Ayam Goreng Bu Tini",
    category: "Makanan",
    subcategory: "Ayam Goreng",
    phone: "0274511111",
    priceRange: [20000, 35000],
    paymentMethods: ["Tunai", "QRIS"],
    lastUpdated: "2025-10-28",
    reviewsList: [/* ... */],
    owner: { name: "Bu Tini", joined: "2024-02-25", verified: true },
    rating: 95,
    reviews: 320,
    location: "Dekat Tugu",
    distance: "5 min",
    priceFrom: 22000,
    latitude: -7.781,
    longitude: 110.368,
    images: [
      "https://images.unsplash.com/photo-1626645737525-375da14d5138?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1562967914-01efa7e87832?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Ayam goreng kampung empuk dengan kremesan gurih. ...",
    details: { type: "Restoran", facilities: ["Parkir", "Toilet", "Lalapan Ambil Sendiri"] },
    tags: ["female_founded", "family_owned", "preserves_cultural_heritage"],
    video_url: videoMakanan,
    products: foodProducts,
  },
  {
    id: 41,
    name: "Toko Wayang Kulit",
    category: "Produk",
    subcategory: "Kerajinan Kulit",
    phone: "081222333555",
    priceRange: [30000, 2000000],
    paymentMethods: ["Tunai", "Transfer Bank"],
    lastUpdated: "2025-10-20",
    reviewsList: [/* ... */],
    owner: { name: "Pak Dalang", joined: "2024-04-22", verified: false },
    rating: 96,
    reviews: 60,
    location: "Kraton",
    distance: "10 min",
    priceFrom: 50000,
    latitude: -7.806,
    longitude: 110.365,
    images: [
      "https://images.unsplash.com/photo-1624622089339-a8c6f2f0c7e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1624622089304-45330368310e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Menjual wayang kulit asli berbagai ukuran...",
    details: { type: "Toko Kerajinan", facilities: ["Workshop", "Edukasi Singkat"] },
    tags: ["fully_handmade", "hand_carved", "preserves_cultural_heritage", "family_owned", "made_to_order", "custom_orders", "personalizable"],
    video_url: videoKerajinan,
    products: [
      { id: "p1", name: "Wayang Kulit Arjuna", price: 750000, description: "Ukuran standar pedalangan, kulit kerbau asli.", image_url: "https://images.unsplash.com/photo-1624622089339-a8c6f2f0c7e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80" },
      { id: "p2", name: "Gantungan Kunci Wayang", price: 30000, description: "Souvenir Punakawan (Semar, Gareng, Petruk, Bagong).", image_url: "https://images.unsplash.com/photo-1624622089304-45330368310e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80" }
    ],
  },
  {
    id: 42,
    name: "Es Buah PK",
    category: "Makanan",
    subcategory: "Dessert",
    phone: "081555666777",
    priceRange: [10000, 15000],
    paymentMethods: ["Tunai", "QRIS"],
    lastUpdated: "2025-10-29",
    reviewsList: [/* ... */],
    owner: { name: "Keluarga PK", joined: "2024-03-02", verified: false },
    rating: 95,
    reviews: 280,
    location: "Pakualaman",
    distance: "15 min",
    priceFrom: 10000,
    latitude: -7.801,
    longitude: 110.3755,
    images: [
      "https://images.unsplash.com/photo-1600091323386-e4a6b10a20f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1504439031068-01d00c3c6f84?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Es buah legendaris dengan isian komplit...",
    details: { type: "Kaki Lima", facilities: ["Banyak Pilihan Topping", "Area Duduk"] },
    tags: ["family_owned", "small_batch"],
    video_url: videoMakanan,
    products: foodProducts,
  },
  {
    id: 43,
    name: "Pusat Gerabah Kasongan",
    category: "Belanja",
    subcategory: "Kerajinan Gerabah",
    phone: "0274371111",
    priceRange: [5000, 1000000],
    paymentMethods: ["Tunai", "QRIS (Sebagian Tenant)"],
    lastUpdated: "2025-10-18",
    reviewsList: [/* ... */],
    owner: { name: "Paguyuban Kasongan", joined: "2024-02-01", verified: true },
    rating: 97,
    reviews: 400,
    location: "Kasongan (Agak ke Selatan)",
    distance: "30 min",
    priceFrom: 5000,
    latitude: -7.846,
    longitude: 110.3472,
    images: [
      "https://images.unsplash.com/photo-1549033391-8c1c463e5b33?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1578904764805-7f5378130835?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Desa wisata yang menjadi pusat kerajinan gerabah dan keramik...",
    details: { type: "Pasar Kerajinan", facilities: ["Banyak Showroom", "Workshop", "Parkir Luas"] },
    tags: ["community_empowerment", "fully_handmade", "locally_sourced_materials", "rural_community", "preserves_cultural_heritage", "custom_orders"],
    video_url: videoKerajinan,
    products: [
      { id: "p1", name: "Pot Gerabah Besar", price: 150000, description: "Pot terakota untuk tanaman besar.", image_url: "https://images.unsplash.com/photo-1549033391-8c1c463e5b33?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80" },
      { id: "p2", name: "Set Cangkir Keramik", price: 80000, description: "Set cangkir dan teko keramik.", image_url: "https://images.unsplash.com/photo-1578904764805-7f5378130835?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80" }
    ],
  },
  {
    id: 44,
    name: "Bengkel Motor Pak Man",
    category: "Jasa",
    subcategory: "Bengkel",
    phone: "081212123434",
    priceRange: [15000, 300000],
    paymentMethods: ["Tunai", "QRIS"],
    lastUpdated: "2025-10-25",
    reviewsList: [/* ... */],
    owner: { name: "Pak Man", joined: "2024-05-16", verified: false },
    rating: 94,
    reviews: 115,
    location: "Jl. Bantul",
    distance: "20 min",
    priceFrom: 20000,
    latitude: -7.818,
    longitude: 110.3615,
    images: [
      "https://images.unsplash.com/photo-1581223681816-a09e1ac7c86a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1621644752281-0f7238a063c1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Bengkel umum non-resmi yang jujur dan terpercaya. ...",
    details: { type: "Bengkel", facilities: ["Ganti Oli", "Servis Ringan", "Tambal Ban"] },
    tags: ["family_owned"],
    video_url: videoJasa,
    products: serviceProducts,
  },
  {
    id: 45,
    name: "Toko Klontong Bu Sri",
    category: "Belanja",
    subcategory: "Warung",
    phone: "0274371122",
    priceRange: [1000, 50000],
    paymentMethods: ["Tunai"],
    lastUpdated: "2025-11-01",
    reviewsList: [/* ... */],
    owner: { name: "Bu Sri", joined: "2024-01-11", verified: false },
    rating: 93,
    reviews: 50,
    location: "Ngampilan",
    distance: "10 min",
    priceFrom: 1000,
    latitude: -7.8025,
    longitude: 110.359,
    images: [
      "https://images.unsplash.com/photo-1590300136236-01f301402a7b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1588977221655-6638549e623c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Warung kelontong yang menjual kebutuhan sehari-hari...",
    details: { type: "Warung", facilities: ["Lengkap", "Harga Eceran"] },
    tags: ["female_founded", "family_owned"],
    video_url: videoJasa,
    products: shopProducts,
  },
  {
    id: 46,
    name: "Lesehan Terang Bulan",
    category: "Makanan",
    subcategory: "Lesehan",
    phone: "081888777666",
    priceRange: [15000, 30000],
    paymentMethods: ["Tunai"],
    lastUpdated: "2025-10-24",
    reviewsList: [/* ... */],
    owner: { name: "Pak Kumis", joined: "2024-08-01", verified: false },
    rating: 92,
    reviews: 180,
    location: "Jl. Malioboro",
    distance: "0 min",
    priceFrom: 20000,
    latitude: -7.7945,
    longitude: 110.3658,
    images: [
      "https://images.unsplash.com/photo-1604251759491-3046f3378174?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Salah satu dari banyak warung lesehan di Malioboro...",
    details: { type: "Lesehan", facilities: ["Makan di Tempat", "Live Music (Musisi Jalanan)"] },
    tags: [],
    video_url: videoMakanan,
    products: foodProducts,
  },
  {
    id: 47,
    name: "Gramedia Sudirman",
    category: "Belanja",
    subcategory: "Toko Buku",
    phone: "0274561234",
    priceRange: [10000, 500000],
    paymentMethods: ["Tunai", "QRIS", "Debit", "Kartu Kredit"],
    lastUpdated: "2025-10-25",
    reviewsList: [/* ... */],
    owner: { name: "Gramedia", joined: "2024-01-15", verified: true },
    rating: 96,
    reviews: 500,
    location: "Jl. Jend. Sudirman",
    distance: "10 min",
    priceFrom: 10000,
    latitude: -7.7836,
    longitude: 110.3705,
    images: [
      "https://images.unsplash.com/photo-1507842217343-583bb7270b66?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1533669061430-65c2e0d7b835?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Toko buku Gramedia terbesar di Yogyakarta. ...",
    details: { type: "Toko Buku", facilities: ["AC", "Kafe", "Alat Tulis", "Parkir"] },
    tags: [],
    video_url: videoJasa,
    products: shopProducts,
  },
  {
    id: 48,
    name: "Klinik Hewan Jogja",
    category: "Jasa",
    subcategory: "Klinik Hewan",
    phone: "0274555666",
    priceRange: [80000, 1000000],
    paymentMethods: ["Tunai", "QRIS", "Debit"],
    lastUpdated: "2025-10-30",
    reviewsList: [/* ... */],
    owner: { name: "Drh. Hewan", joined: "2024-03-30", verified: true },
    rating: 97,
    reviews: 160,
    location: "Jl. Kaliurang (Bawah)",
    distance: "15 min",
    priceFrom: 80000,
    latitude: -7.7765,
    longitude: 110.376,
    images: [
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1596797882510-0da13101d21c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Klinik dokter hewan 24 jam dengan fasilitas UGD...",
    details: { type: "Klinik Hewan", facilities: ["Dokter Jaga", "Grooming", "Pet Shop"] },
    tags: [],
    video_url: videoJasa,
    products: serviceProducts,
  },
  {
    id: 49,
    name: "Toko Jamu Instan",
    category: "Produk",
    subcategory: "Herbal",
    phone: "081999888777",
    priceRange: [8000, 50000],
    paymentMethods: ["Tunai", "QRIS"],
    lastUpdated: "2025-10-21",
    reviewsList: [/* ... */],
    owner: { name: "Toko Herbal", joined: "2024-05-20", verified: false },
    rating: 94,
    reviews: 70,
    location: "Pasar Beringharjo",
    distance: "2 min",
    priceFrom: 10000,
    latitude: -7.7986,
    longitude: 110.366,
    images: [
      "https://images.unsplash.com/photo-1556706990-0f31750c48d3?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "httpsg.com/photo-1620921282046-e179e0a16c88?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Menjual berbagai macam jamu dan rempah dalam bentuk bubuk instan. ...",
    details: { type: "Toko Herbal", facilities: ["Bisa Kirim", "Lengkap"] },
    tags: ["locally_sourced_materials", "natural_dyes", "preserves_cultural_heritage", "small_batch"],
    video_url: videoKerajinan,
    products: shopProducts,
  },
  {
    id: 50,
    name: "Jasa Desain Grafis 'Logo Cepat'",
    category: "Jasa",
    subcategory: "Desain",
    phone: "085112341234",
    priceRange: [150000, 500000],
    paymentMethods: ["Transfer Bank", "QRIS"],
    lastUpdated: "2025-10-28",
    reviewsList: [/* ... */],
    owner: { name: "Mas Grafis", joined: "2024-08-15", verified: false },
    rating: 95,
    reviews: 40,
    location: "Kotabaru",
    distance: "10 min",
    priceFrom: 200000,
    latitude: -7.7855,
    longitude: 110.3735,
    images: [
      "https://images.unsplash.com/photo-1609921141834-7d169ae659e9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
      "https://images.unsplash.com/photo-1611162617213-7d724e0f2042?ixlib=rb-4.0.3&auto=format&fit=crop&w=1974&q=80",
    ],
    description: "Freelancer jasa desain logo, brosur, dan kebutuhan branding UMKM. ...",
    details: { type: "Jasa Desain", facilities: ["Konsultasi Online", "Revisi 3x"] },
    tags: ["social_enterprise", "personalizable", "custom_orders", "made_to_order"],
    video_url: videoJasa,
    products: serviceProducts,
  },
];